from typing import List

class Sasdie:
    macarte = ...

    def setLogin(self, email: str) -> None: ...
    def setPasswd(self, password: str) -> None: ...
    def publierpage_html(self, webpage_content: str) -> bool: ...
    def lectureDonnéesCourante(self) -> str: ...
    def lireDonneesPollutionRPI(self) -> List[str]: ...
    def lireDonneesPollution(self, filename: str) -> List[str]: ...
    def lireCoordonneesGPS(self) -> str: ...
    def macle(self) -> str: ...
    def creerCarte(self): ...
    def ajoutCercleSurLaCarte(self, lat: str, lon: str, diameter: int, label: str): ...
    def ajoutMarqueurSurLaCarte(self): ...
    def produireHTMLCarte(self, lat: str, lon: str, label: str): ...
