on:
  workflow_dispatch:
  ##schedule: [{cron: "0,30 * * * *"}]
  push: {branches: ["master"]}

jobs:
  readme-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: run
        run: make README.md

      - name: setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull

      - name: running script
        run: |
          git commit -am ":memo: Update README" || echo "No changes to commit"
          git push || echo "No changes to push"
